# Generated by Django 4.2.7 on 2024-01-04 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='assignedDoctor',
            new_name='assignedDoctor_id',
        ),
    ]
