# Generated by Django 4.2.7 on 2024-01-05 07:27

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0002_rename_assigneddoctor_patient_assigneddoctor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='workDays',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday'), ('Sun', 'Sunday')], max_length=100),
        ),
    ]
